### PR TITLE
add sdk etc

### PR DESCRIPTION
**Pull request by cfsnook**

### CODE REVIEW

**Comment by cfsnook** [comment]
This feature does not get grouped with other uml-b plugins even though it has the same icon image. 
I presume because i set the provider to UoS and Sandia... shall i put just UoS and mention Sandia in the about text?

**Comment by cfsnook** [comment]
I have now updated the copyright headers to EPL V2.0

**Comment by cfsnook** [comment]
It still fails because we need to release SCXML EMF as it is a dependency

**Comment by cfsnook** [comment]
I am waiting for Karla to agree the about statement anyway - so don't approve this yet

**Review by tshoang — APPROVED** [review]
Looks great

**Pull request merged**
